[WIP] users should be able to see status of their request
andela/archangel-backend pull request #28
Opened 2019-09-08 15:44 UTC by captainamiedi

#### What does this PR do?

- having a CRUD operations that enable a use see his request status

#### Description of Task to be completed?

- users can see the status of their request

- only users is authorize for these operation

#### How should this be manually tested?

- POSTMAN

#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?

- #167730642

#### Screenshots (if appropriate)
#### Questions:

2019-09-09 14:00 UTC, chuksjoe commented on src/controllers/travelControllers.js
> +import { async } from 'regenerator-runtime';
you don't need this line, as it really does nothing

2019-09-09 14:01 UTC, chuksjoe requested changes
Good after @captainamiedi, please, why do you have so many commits in your PR?
I will suggest you `squash` them all into one commit so that `rebasing` wouldn't be a headache.

Afterward, you can be updating the commit with `git commit --amend` after staging your changes.

2019-09-11 13:03 UTC, Marshalheri commented
Good day team mate.
Please while you work on resolving the conflicts that is present in your work i request that you carefully see what i have done so far based on the changes that we need to implement. 
So that our works can all be in sync with each other.
Thanks

2019-09-12 15:52 UTC, iakhator approved these changes
looks good.

2019-09-12 15:52 UTC, merged