ft(return-trip-request): implement create return trip request feature
andela/archangel-backend pull request #35
Opened 2019-09-13 10:48 UTC by Marshalheri

**What does this PR do?**

Adds an endpoint for users to make a return trip request

**Description**

- Modify the travelController.js to include the function to handle the request for creating a return trip.
- Modify travelServices.js to include services to implement the functionality of the return trip controller.
- Create validation for the return trip travel request route.
- Create a route for the return trip travel request.
- write test to test the functionalities of the return trip request route

**How can this be manually tested**

Clone the repo
Run npm install to install dependencies, setup database and run npm run dev
Make a post request to localhost:5000/api/v1/travel/returntrip and pass in the values to make a return trip request

**Relevant Pivotal tracker stories**

#167730639

2019-09-13 11:43 UTC, captainamiedi approved these changes
nice job mate. you have strict validations.

2019-09-13 11:51 UTC, Marshalheri commented
> nice job mate. you have strict validations.

how do you mean please?

2019-09-13 12:21 UTC, danoseun reviewed
You have done a really nice job bro but why did you spread the req.body object into the travelObj variable when you already destructured the contents of the request body and added them to the variable? Is it an intentional repetition?

2019-09-13 12:34 UTC, Marshalheri commented
> You have done a really nice job bro but why did you spread the req.body object into the travelObj variable when you already destructured the contents of the request body and added them to the variable? Is it an intentional repetition?

Thanks for your feedback.
I actually just spread the req.body into the travelObj, i removed the part where i did the destructuring before because it appeared redundant based on the conversation we had with the TTL during code review.

2019-09-13 13:04 UTC, chuksjoe requested changes
Great work bro. Just look into the other comments I dropped inline. Also, try to attend to the Hound-CI flags.

2019-09-13 13:04 UTC, chuksjoe commented on src/services/travelServices.js
> +export const returnTripService = async (travelRequest) => {
this function is doing the same thing with the `onewayTripService`. why not reuse the above and maybe give it a more generic name like `createTravelService` to avoid redundant codes

2019-09-13 13:04 UTC, chuksjoe commented on src/tests/mockData.js
> +var presentDate = new Date();
why are you using `var`? It should be either `const` or `let`

2019-09-14 11:42 UTC, Kaytbode commented on src/tests/mockData.js
> +var returnDate = `${newFutureDate.getFullYear()}-${ISOMonth[newFutureDate.getMonth()]}-${newFutureDate.getDate()}`;
@Marshalheri  Love your tenacity and mentality on handling this task

please attend to the use of var instead of let or const

2019-09-14 11:43 UTC, Kaytbode requested changes
@Marshalheri  You have put it a lot into this task.. well done

Please attend to the hound's yearnings

2019-09-14 19:07 UTC, merged